// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqzShi4KJkL8SSDE2eAZpqxhu7kAnUQEY',
    appId: '1:967106231298:web:301de9238ae0838e623b1b',
    messagingSenderId: '967106231298',
    projectId: 'chatappzouaoui',
    authDomain: 'chatappzouaoui.firebaseapp.com',
    storageBucket: 'chatappzouaoui.firebasestorage.app',
    measurementId: 'G-5D5DKGZXGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmuNAsYyMywNlC5LOLIQxEED6aa3rOl88',
    appId: '1:967106231298:android:ec3fa97e80fc4941623b1b',
    messagingSenderId: '967106231298',
    projectId: 'chatappzouaoui',
    storageBucket: 'chatappzouaoui.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfroBHLH9OSns7hV3l9xjUF3fJhBKeXHY',
    appId: '1:967106231298:ios:4233e16219d097b8623b1b',
    messagingSenderId: '967106231298',
    projectId: 'chatappzouaoui',
    storageBucket: 'chatappzouaoui.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfroBHLH9OSns7hV3l9xjUF3fJhBKeXHY',
    appId: '1:967106231298:ios:4233e16219d097b8623b1b',
    messagingSenderId: '967106231298',
    projectId: 'chatappzouaoui',
    storageBucket: 'chatappzouaoui.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqzShi4KJkL8SSDE2eAZpqxhu7kAnUQEY',
    appId: '1:967106231298:web:16858819a3ec3e9a623b1b',
    messagingSenderId: '967106231298',
    projectId: 'chatappzouaoui',
    authDomain: 'chatappzouaoui.firebaseapp.com',
    storageBucket: 'chatappzouaoui.firebasestorage.app',
    measurementId: 'G-66K1DXXK82',
  );
}
